controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_fl_joint", "wheel_rl_joint"]
    right_wheel_names: ["wheel_fr_joint", "wheel_rr_joint"]
    wheel_separation: 0.50
    wheel_radius: 0.15